### ISSUE TITLE
Add automatic package bibliography

### ISSUE THREAD

**Issue by RaymondBalise** [RaymondBalise/rUM#3]
Tweak YAML:
```
bibliography: [references.bib, packages.bib]
```

Add this to reference section of Rmd
````
```{r include=FALSE}
# automatically create a bib database for loaded R packages & rUM
knitr::write_bib(
  c(
    .packages(), 
    'rUM'
  ), 
  'packages.bib'
)
```
````

Remove call to reference gist. Write blank file instead.

**Comment by gabrielodom** [comment]
Not reopening this issue, but I think we should add a comment in a vignette about what to do if the `.bib` files are saved in a different location on the user's machine. For example, I have all my `.bib` and `.csl` files saved in a higher-level directory for all the papers related to a large project. I might have 4-5 different manuscripts that I'm writing that use very similar citations. In this case, I want the `packages.bib` file to update in a different location. Therefore, I add this option in the `knitr::write_bib()` call:
```
  # "packages.bib"
  file = "../../bib/DAB_packages_20241204.bib"
```
I'm not sure how many other people this would affect, but it might make sense to at least reference the option.
